//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public int EmpId { get; set; }
        public string InEmpImage { get; set; }
        public Nullable<double> InLatitude { get; set; }
        public Nullable<double> InLongitude { get; set; }
        public Nullable<int> InDistance { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public string OutEmpImage { get; set; }
        public Nullable<double> OutLatitude { get; set; }
        public Nullable<double> OutLongitude { get; set; }
        public Nullable<int> OutDistance { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
