//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Areas = new HashSet<Area>();
            this.Attendances = new HashSet<Attendance>();
            this.Cities = new HashSet<City>();
            this.EmpGroups = new HashSet<EmpGroup>();
            this.Regions = new HashSet<Region>();
        }
    
        public int EmpId { get; set; }
        public string EmpNum { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> MaxDistFromStore { get; set; }
        public Nullable<int> validationText { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<short> WeeklyOff { get; set; }
        public Nullable<System.TimeSpan> OfficeStart { get; set; }
        public Nullable<System.TimeSpan> OfficeEnd { get; set; }
        public string ClientEmpNum { get; set; }
        public string EmpImage { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<City> Cities { get; set; }
        public virtual Designation Designation1 { get; set; }
        public virtual ICollection<EmpGroup> EmpGroups { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<Region> Regions { get; set; }
    }
}
