//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.EmpGroups = new HashSet<EmpGroup>();
            this.OfferGroups = new HashSet<OfferGroup>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<EmpGroup> EmpGroups { get; set; }
        public virtual ICollection<OfferGroup> OfferGroups { get; set; }
    }
}
