//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDS.Socio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public Offer()
        {
            this.OfferGroups = new HashSet<OfferGroup>();
        }
    
        public int OfferId { get; set; }
        public string sender { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> sent { get; set; }
    
        public virtual ICollection<OfferGroup> OfferGroups { get; set; }
    }
}
