//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<System.TimeSpan> StoreOpen { get; set; }
        public Nullable<System.TimeSpan> StoreClose { get; set; }
        public string Address { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<short> StoreOff { get; set; }
        public string StoreCode { get; set; }
    
        public virtual Area Area1 { get; set; }
        public virtual City City1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Region Region1 { get; set; }
    }
}
