//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDS.Socio
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpInTimeAnalysi
    {
        public int Id { get; set; }
        public string TimeRange { get; set; }
        public Nullable<int> PercentPeople { get; set; }
    }
}
